/**
 * Disposable / throwaway email domain blocklist.
 * Used in /api/auth/pre-register to reject registrations from known spam domains.
 *
 * To extend: add the domain string to BLOCKED_DOMAINS and redeploy.
 */

export const BLOCKED_DOMAINS = new Set([
  // ── Major disposable email services ───────────────────────────────────────
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '10minutemail.co.uk', '10minutemail.de', '10minutemail.ru',
  'temp-mail.org', 'temp-mail.io', 'tempmail.com', 'tempmail.net',
  'tempmail.de', 'tempmail.eu', 'tempail.com',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamail.de', 'guerrillamail.info',
  'grr.la', 'spam4.me', 'sharklasers.com', 'guerrillamailblock.com',
  'mailinator.com', 'mailinator2.com', 'mailinator.net', 'mailinator.org',
  'trashmail.com', 'trashmail.at', 'trashmail.io', 'trashmail.me',
  'trashmail.net', 'trashmail.org', 'trashmail.xyz',
  'yopmail.com', 'yopmail.fr', 'cool.fr.nf', 'jetable.fr.nf',
  'nospam.ze.tc', 'nomail.xl.cx', 'mega.zik.dj', 'speed.1s.fr',
  'courriel.fr.nf', 'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf',
  'dispostable.com', 'throwam.com', 'throwam.net',
  'mailnull.com', 'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spamex.com', 'spamfree24.org', 'spamhereplease.com',
  'spamspot.com', 'spamthisplease.com',
  'fakeinbox.com', 'fakeinbox.net', 'fakemail.fr',
  'spambox.us', 'spambox.info', 'spambox.irishspringrealty.com',
  'getairmail.com', 'mailexpire.com', 'mailnew.com', 'maileater.com',
  'mailnesia.com', 'mailnull.com', 'mailseal.de',
  'discard.email', 'discardmail.com', 'discardmail.de',
  'throwaway.email', 'throwam.com', 'throwam.net',
  'maildrop.cc', 'mailfall.com', 'mailfreeonline.com',
  'mailme.lv', 'mailme24.com', 'mailmetrash.com',
  'mailtome.de', 'mailzilla.org', 'mailzilla.com',
  'mt2009.com', 'mt2014.com', 'mt2015.com',
  'mytempemail.com', 'my10minutemail.com', 'mytrashmail.com',
  'nobulk.com', 'noclickemail.com', 'nogmailspam.info',
  'nomail.pw', 'nomail.xl.cx', 'nomail2me.com',
  'nospammail.net', 'nospamfor.us', 'notmailinator.com',
  'obobbo.com', 'odaymail.com',
  'pookmail.com', 'poofy.org',
  'qq.com.cn', 'quickmail.nl',
  'rcpt.at', 'reallymymail.com',
  'safetymail.info', 'safetypost.de', 'samsclass.info',
  'sandelf.de', 'saynotospams.com', 'selfdestructingmail.com',
  'sendspamhere.com', 'sharklasers.com', 'shitmail.me',
  'shitware.nl', 'sibmail.com', 'skeefmail.com',
  'slippery.email', 'smellfear.com', 'snakemail.com',
  'sofimail.com', 'sogetthis.com', 'soodonims.com',
  'spamavert.com', 'spambob.com', 'spambob.net', 'spambob.org',
  'spamcannon.com', 'spamcannon.net', 'spamcero.com',
  'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org', 'spamday.com',
  'spamdecoy.net', 'spamfree.eu', 'spamfree24.de',
  'spamfree24.eu', 'spamfree24.info', 'spamfree24.net',
  'spamgloben.com', 'spamherelots.com', 'spamify.com',
  'spaminator.de', 'spaml.com', 'spaml.de',
  'spammotel.com', 'spamobox.com', 'spamoff.de',
  'spampop.net', 'spamserver.de', 'spamslicer.com',
  'spamsub.com', 'spamthisplease.com', 'spamtrail.com',
  'spamwc.de', 'spamwc.net', 'spamwc.org',
  'spoofmail.de', 'squizzy.de', 'squizzy.eu',
  'startkeys.com', 'stinkefinger.net',
  'super-auswahl.de', 'supergreat.com', 'supermailer.jp',
  'superstachel.de', 'suremail.info',
  'svk.jp', 'sweetxxx.de',
  'tafmail.com', 'tagyourself.com',
  'techemail.com', 'techgroup.me',
  'telecomix.pl', 'tempalias.com',
  'tempe-mail.com', 'tempemail.com', 'tempemail.net',
  'tempi.de', 'temporamail.com',
  'temporary-mail.net', 'temporaryemail.net', 'temporaryemail.us',
  'temporaryinbox.com', 'temporarymail.org',
  'tempthe.net', 'ternaopoli.cf',
  'thanksnospam.info', 'thankyou2010.com',
  'thc.st', 'thisisnotmyrealemail.com',
  'throam.com', 'thrott.com',
  'throwam.com', 'throwam.net', 'throwamailaway.com',
  'tittbit.in', 'tmail.com', 'tmail.ws',
  'tmailinator.com', 'tokem.co', 'toomail.biz',
  'topranklist.de', 'tradermail.info', 'trash-amil.com',
  'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trash-mail.ga', 'trash-mail.io', 'trash-mail.net',
  'trash2009.com', 'trash2010.com', 'trash2011.com',
  'trashdevil.com', 'trashdevil.de',
  'trashmail.at', 'trashmail.com', 'trashmail.de',
  'trashmail.io', 'trashmail.me', 'trashmail.net',
  'trashmail.org', 'trashmail.xyz',
  'trashmailer.com', 'trashmailer.de',
  'trbvm.com', 'trillianpro.com', 'tryalert.com',
  'turual.com', 'twinmail.de', 'twoweirdtricks.com',
  'tyldd.com', 'umail.net', 'unimail.xyz',
  'unlimit.com', 'unmail.ru', 'uroid.com',
  'uroid.net', 'uroid.org', 'uroid.uk',
  'veryrealemail.com', 'viditag.com', 'viewcastmedia.com',
  'viewcastmedia.net', 'viewcastmedia.org', 'vkcode.ru',
  'vomoto.com', 'vpn.st',
  'webemail.me', 'webide.de', 'weg-werf-email.de',
  'wegwerf-emails.de', 'wegwerfadresse.de', 'wegwerfemail.com',
  'wegwerfemail.de', 'wegwerfemail.info', 'wegwerfemail.net',
  'wegwerfemail.org', 'wegwerfmail.de', 'wegwerfmail.info',
  'wegwerfmail.net', 'wegwerfmail.org',
  'wetrainbayarea.com', 'wetrainbayarea.org',
  'whyspam.me', 'wile.de', 'willhackforfood.biz',
  'willselfdestruct.com', 'winemaven.info', 'wiskii.com',
  'wuzupmail.net', 'xagloo.com', 'xemaps.com',
  'xents.com', 'xmaily.com', 'xoxy.net',
  'xyzmail.men', 'yamail.com',
  'yarnpedia.ga', 'yentzscholarship.xyz',
  'yodx.ro', 'yopmail.com', 'youmailr.com',
  'ypmail.webarnak.fr.eu.org', 'yuurok.com',
  'z1p.biz', 'za.com', 'zain.site', 'zanichelli.tk',
  'zehnminutenmail.de', 'zep-hyr.com', 'zipcad.com',
  'zipmail.com.br', 'zippiex.com',
  'zoemail.com', 'zoemail.net', 'zoemail.org',
  'zomg.info', 'zweitgeist.de',
  // ── Common spam domains seen in the wild ─────────────────────────────────
  'icotz.com', 'luxudata.com',
  'inboxbear.com', 'inboxclean.com', 'inboxdesign.be',
  'inboxed.pw', 'inboxkitten.com', 'inboxproxy.com',
  'mohmal.com', 'momomail.com',
  'binkmail.com', 'blnkt.net', 'bobmail.info',
  'bodhi.lawlita.com', 'bofthew.com', 'boun.cr',
  'brefmail.com', 'bsnow.net', 'bugmenot.com',
  'bumpymail.com', 'buri.ga',
  'cachedot.net', 'casualdx.com', 'catchall.net',
  'ce.mintemail.com', 'cek.pm', 'cellurl.com',
  'centermail.at', 'centermail.com', 'changeip.net',
  'chong-mail.com', 'chong-mail.net', 'chong-mail.org',
  'ckiso.com', 'cl-cl.org', 'clrmail.com',
  'cobarekyo1.ml', 'cock.li', 'cock.lu',
  'codeandscotch.com', 'codeforums.net', 'coldemail.info',
  'cool.fr.nf', 'correo.blogos.net',
  'creditcardcc.com', 'crot.cf', 'cs.email',
  'curryworld.de', 'cust.in', 'cuvox.de',
  'd3p.co.uk', 'dacoolest.com', 'daemsteam.com',
  'daksite.ml', 'daktronics.com.br',
  'dayrep.com', 'dbunker.com', 'dcemail.com',
  'deadaddress.com', 'dealrek.com', 'deagot.com',
  'delikkt.de', 'der-kombi.de', 'der-postillon.com',
  'derkombi.de', 'derluxuswagen.de', 'desoz.com',
  'despam.it', 'despammed.com', 'devnullmail.com',
  'dflx.ch', 'dfgh.net', 'dfwatson.com',
  'dharmatel.net', 'didikselowber.cf', 'die-besten-bilder.de',
  'die-genossen.de', 'die-hoffnung.com', 'die-hummel.de',
  'die-maker.de', 'diemailbox.de', 'digital-email.com',
  'digitalbrain.com', 'digitalmail.info', 'digitalmariachis.com',
  'dingbone.com', 'disaq.com',
  // ── Catch-all: more known spam TLDs used for bots ────────────────────────
  'emkei.cz', 'emailx.at.hm',
  'emailfake.com', 'emailfake.ml', 'emailfake.ga',
  'emailgenerator.de', 'emailgo.de', 'emailias.com',
  'emailinfive.com', 'emailisvalid.com', 'emailkarten.de',
  'emaillo.com', 'emailmiser.com', 'emailoneonline.com',
  'emailproxsy.com', 'emailresort.com', 'emailsensei.com',
  'emailsio.com', 'emailspam.me', 'emailtemp.org',
  'emailto.de', 'emailwarden.com', 'emailx.at.hm',
  'emailxfer.com', 'emailz.gq', 'emirmail.ga',
  'emkei.ga', 'emkei.ml',
  'eml.pp.ua', 'emlhub.com', 'emlpro.com',
  'emltmp.com', 'emz.net', 'enterto.com',
])

/**
 * Returns true if the email domain is in the blocklist.
 */
export function isBlockedDomain(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase().trim()
  if (!domain) return true
  return BLOCKED_DOMAINS.has(domain)
}

/**
 * Returns true if the email username looks auto-generated by a bot.
 * Pattern: 5+ consecutive digits in the local part (e.g. kelek62373@..., hatid44185@...)
 */
export function looksLikeBot(email: string): boolean {
  const local = email.split('@')[0] ?? ''
  return /\d{5,}/.test(local)
}
